version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies
      - npm i
  build:
    commands:
      - echo Building the project
      - npm run build
artifacts:
  files:
    - 'dist/**/*'  # This will include all files in the dist directory
  base-directory: .  # Upload files directly to the root of the S3 bucket
