version: 0.2

phases:
  install:
    runtime-versions:
      node: 18
  pre_build:
    commands:
      - echo Installing dependencies
      - npm i
  build:
    commands:
      - echo Building the project
      - npm run build
artifacts:
  files:
    - dist/*
